# Generated by Django 4.2.2 on 2025-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='images'),
        ),
    ]
